name: Wake Arena Audit
run-name: ${{ github.actor }} prepared Wake Arena PR
on:
  push:
    branches:
      - master #todo change to your main branch
jobs:
  perform-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
        with:
          submodules: recursive # Git submodules installation, remove if not valid for your project
      - name: Setup Wake
        uses: Ackee-Blockchain/wake-setup-action@0.1.0
      - name: Setup Wake Arena
        uses: Ackee-Blockchain/wake-arena-setup-action@0.1.1
      - name: Perform audit
        env:
          WAKE_ARENA_API_KEY: ${{ secrets.WAKE_ARENA_API_KEY }}
        run: wake-arena check --name "${{ github.event.head_commit.message }}" --project "7IpvFufZ"
